### ISSUE TITLE
does the sms receive and send work on iOS?

### ISSUE THREAD

**Issue by 0xSECRETenv** [MuminjonGuru/Mastering-FireMonkey-Delphi#3]
I mean your repo here: https://github.com/MuminjonGuru/Mastering-FireMonkey-Delphi/tree/master/Receive%20%26%20Send%20SMS%20-%20FMX%20Android

**Comment by MuminjonGuru** [comment]
I am not sure, though... I think you can't retrieve SMS on iOS devices, kind of privacy restrictions.
